### ISSUE TITLE
Pebble double Heart Rate

### ISSUE THREAD

**Issue by fnobilia** [RADAR-CNS/RADAR-Schemas#10]
The pebble device provides two Heart Rate: one raw and one precomputed. HR schema is not able to capture this different. A solution could be adding a new field inside the `header` that states if the retrieved informations come from raw data or not.
```json
"header":
	{
		"descriptive_statistic":"union",
		"unit":"beats_per_min",
		"source":[ "raw" | "precomputed" ],
		"effective_time_frame":
		{
			"start_date_time":"1970-01-18T03:03:50Z",
			"end_date_time":"1970-01-18T03:04:10Z"
		}
	},
```

**Comment by blootsvoets** [comment]
In the Android code, I treat both of them as heart rates but send them to different streams. Perhaps naming the algorithm would be good? something like `"algorithm": null`,` "algorithm": "pebble2_filtering"`. As far as I know, Pebble does not expose the actual algorithm they use. For the empatica we could use a custom/known algorithm based on the PPG, and return that algorithm here?

**Comment by fnobilia** [comment]
The `algorithm` provides more freedom than `source`. But then we need to send this value from the source since it might be related to the firmware.

**Comment by blootsvoets** [comment]
Good point. Since the firmware version is dynamic, would it make sense to send this for devices we can get it from, perhaps in a separate stream? If firmware bug/change becomes known afterwards, we can eliminate only the affected data.

**Comment by fnobilia** [comment]
Maybe is better to create a schema for the sources like this:
```json
{
	"header":
	{
		"firmware": {"type": "string"},
		"algorithm": {"type": "string"},
		"time": {"type": "double"},
		"timeReceived": {"type": "double"},
	},
	"sample":[ {
		"value":{"type": "Schema of current sensor"}
	}]
}
```
If we access data we need the firmware / algorithm information. It should be easier having everything within one message than joining different topics.

**Comment by blootsvoets** [comment]
Unless we have evidence otherwise (known bug/algorithm changes), the firmware version is not going to be consequential for the data. It's good to know so we can update/invalidate the data afterwards. The update frequency of the separate stream is going to be very low, and hopefully not even used. I'd prefer not sending it again every message. The algorithm can likewise be updated in our data store if we know the firmware version actually affects it. In other words, I'd prefer the device to send only the minimal amount of data required. On the REST API side we can always add more metadata if we think it's relevant, if needed from a different stream/API call.

From a user/design perspective: what would be actionable? The firmware version of each individual data point or time windows in which certain firmware was used?

**Comment by fnobilia** [comment]
Let's start simple. We update the pebble schemas set creating a single schema for heart rate containing raw and preprocessed data. Then from the rest point of view we add the `"data_type":[ "raw" | "precomputed" ],` field.

I do not mark the issue as resolved. In this way we can truck the idea of adding an `algorithm` field and a `firmware` topic.

**Comment by blootsvoets** [comment]
Is this resolved for now?

**Comment by fnobilia** [comment]
Partially solved. No notion of `algorithm` and `firmware`
