### ISSUE TITLE
Schema for Kafka Key Object

### ISSUE THREAD

**Issue by afolarin** [RADAR-CNS/RADAR-Schemas#2]
Each Kafka Topic commit includes an [offset + Key + Message Value].  The Key Object which will include some metadata  (participant-id, device, etc.) or reference a record in a metadata store. Should there be a schema describing the key objects for each of the data streams in the same way that the value part of the message will have schema?

If so we should also consider this here. @RADAR-CNS/backend-team

**Comment by blootsvoets** [comment]
For compactness of the data, I'd opt for a single opaque ID or token as a key, this also makes any additional metadata easy to retrieve. It does require an additional lookup any time the metadata of a device is needed during processing (I'm not yet sure how often that would be). It also prevents any schema incompatibilities for the keys, e.g., the ingestion clients do not have to be aware of the key schema. The processors only need to be aware of the schema of the metadata store.

**Comment by fnobilia** [comment]
If we use Avro to establish communications during the injestion, the client cannot be aware of the used schema for data. Adding a new schema for the key is not complex and removes the lookup operation. Furthermore the data dissemination across partitions is not compromised, since Kafka will apply an hash function on this composed key.

**Comment by blootsvoets** [comment]
Using `MeasurementKey` now for data and `WindowedKey` for aggregated data.
