### ISSUE TITLE
Radar Questionnaire Schema

### ISSUE THREAD

**Issue by afolarin** [RADAR-CNS/RADAR-Schemas#5]
RADAR-Schemas/RADAR-Questionnaire/config.md  1d8481898ecf2d91fa882d9943265d5495905246

@herkulano this only inclusive of what is necessary to move forward with the present questionnaire builder (specifically for the PHQ8)? 

Also what do you need from the group here.

cc/ @kerzmaximilian

**Comment by afolarin** [comment]
@herkulano I think one thing that's missing is the indication that a filed is "mandatory" or "required".

**Comment by herkulano** [comment]
@afolarin good point. right now the application is considering all questions as "required". 

@kerzmaximilian we need to design how this will look like in the UI.

Added #6

**Comment by kerzmaximilian** [comment]
@herkulano from an implementation perspective, is it easy to add the required/optional feature later on? For now lets assume that every question is required, and needs to be answered in order to move on to the next question. Most questionnaires will be modelled on clinically validated questionnaires, which usually require all questions being answered.

**Comment by herkulano** [comment]
@kerzmaximilian yes, that's the current implemented behavior. all questions are required and the user cannot go to the next question without completing the current question.

**Comment by afolarin** [comment]
OK I think this is fine for now, we might soon though find we need to have both mandatory and non-mandatory options.
